apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-app-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/danilouchoa/pobi.git
    targetRevision: main
    path: helm/finance-app
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
      parameters:
        - name: backend.image.tag
          value: "stable"
        - name: frontend.image.tag
          value: "stable"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore HPA-managed replicas
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas  # Ignore HPA-managed replicas
