docs:
  - files:
      - '**/*.md'
      - 'README.md'
      - 'docs/**'

tests:
  - files:
      - '**/*.spec.js'
      - '**/*.test.js'
      - '**/*.spec.ts'
      - '**/*.test.ts'
      - '**/*.spec.tsx'
      - '**/*.test.tsx'

backend:
  - files:
      - 'backend/**'
frontend:
  - files:
      - 'frontend/**'

api:
  - files:
      - 'backend/src/routes/**'
      - 'backend/src/middlewares/**'
      - 'backend/src/index.ts'

infra:
  - files:
      - 'backend/scripts/**'
      - 'frontend/scripts/**'
      - 'backend/prisma/**'
      - 'docker-compose.yaml'
      - '.env*'

ci:
  - files:
      - '.github/workflows/**'
      - '.github/actions/**'
      - '.husky/**'

config:
  - files:
      - '.eslintrc*'
      - '.prettierrc*'
      - 'tsconfig.json'
      - 'tailwind.config.*'
      - 'postcss.config.*'
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'

dependencies:
  - files:
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
